baseURL = "https://n3k0lai.github.io"
languageCode = "en-us"
title= "n3k0lai"

[params]
  copyrighthtml = "Copyright &#xA9; 2023 Nicholai Goodall. All Rights Reserved."
  twitteruser = "n3k0lai"
  twitchuser = "n3k0lai"
  seventvid = "62526c406e0665dc19502ce7"

[build]
  writeStats = true