particlesJS("particles-js", {
  "particles":{
    "number":{
      "value":80,
      "density":{
        "enable":true,
        "value_area":800
      }
    },
    "color":{
      "value":"#d442f4"
    },
    "shape":{
      "type":"circle"
    },     
    "opacity":{
      "value":0.5,
      "random":true,
      "anim":{
        "enable":true,
        "speed":0.5,
        "opacity_min":0.1,
        "sync":false
      }
    },
    "size":{
      "value":3,
      "random":true,
      "anim":{
        "enable":false,
        "speed":40,
        "size_min":0.1,
        "sync":false
      }
    },     
    "line_linked":{
      "enable":true,
      "distance":50,
      "color":"#fff",
      "opacity":0.3,
      "width":1
    },
    "move":{
      "enable":true,
      "speed":4,
      "direction":"top",
      "random":false,
      "straight":false,
      "out_mode":"out",
      "bounce":false,
      "attract":{
        "enable":true,
        "rotateX":600,
        "rotateY":1200
      }
    }
  },
  "interactivity":{
    "events":{
      "onhover":{"enable":false},
      "onclick":{"enable":false},
      "resize":false
    }
  },
  "retina_detect":true
});
